# Generated by Django 6.0.4 on 2026-04-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('total_participations', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('average_market_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('participants', models.ManyToManyField(related_name='tenders', to='tenders.company')),
                ('winner_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to='tenders.company')),
            ],
        ),
    ]
