# Generated by Django 6.0.4 on 2026-04-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_company_options_alter_tender_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderriskanalysis',
            name='fake_competition_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.company')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender')),
            ],
            options={
                'ordering': ['bid_price', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tender', 'company'), name='unique_tender_company_bid')],
            },
        ),
    ]
