# Generated by Django 6.0.4 on 2026-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tenderriskanalysis_ai_summary_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenderbid',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
