# Generated by Django 6.0.4 on 2026-04-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_company_external_id_tender_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySuspicionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('suspicion_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('price_score', models.PositiveIntegerField(default=0)),
                ('failed_delivery_score', models.PositiveIntegerField(default=0)),
                ('consecutive_wins_score', models.PositiveIntegerField(default=0)),
                ('fake_competition_score', models.PositiveIntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspicion_analysis', to='tenders.company')),
            ],
            options={
                'ordering': ['-total_score', 'company__name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySuspicionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='tenders.companysuspicionanalysis')),
            ],
            options={
                'ordering': ['-score', '-created_at', '-id'],
            },
        ),
    ]
