# Generated by Django 6.0.4 on 2026-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_companysuspicionanalysis_companysuspicionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysuspicionanalysis',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
